// Generated by lazuli types
// DO NOT EDIT MANUALLY

export interface User {
  id: number;
  name: string;
}

// RPC request/response types (from Resource.rpc)
export interface RpcRequests {
  "UsersResource#rpc_index": undefined;
}

export interface RpcResponses {
  "UsersResource#rpc_index": User[];
}
