// Generated by lazuli types
// DO NOT EDIT MANUALLY
import type { RpcRequests, RpcResponses } from "../client.d.ts";

export type RpcKey = keyof RpcResponses & keyof RpcRequests;

export type RpcClientOptions = {
  baseUrl?: string;
  headers?: HeadersInit;
};

export async function rpc<K extends RpcKey>(
  key: K,
  params: RpcRequests[K],
  options: RpcClientOptions = {},
): Promise<RpcResponses[K]> {
  const baseUrl = options.baseUrl ?? "";
  const res = await fetch(`${baseUrl}/__lazuli/rpc`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      ...(options.headers ?? {}),
    },
    body: JSON.stringify({ key, params }),
  });

  if (!res.ok) {
    throw new Error(`RPC failed (${res.status}): ${await res.text()}`);
  }

  return (await res.json()) as RpcResponses[K];
}
